{% set version = '0.9.3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rzmq
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rzmq_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rzmq/rzmq_{{ version }}.tar.gz
  sha256: ab6f6da1fcd0c11003517a21bd85f5c56495e6926542db3fb320f3901f292b13

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - {{native}}zeromq 4.2.*     # [not win]
    - {{native}}zeromq 4.1.*     # [win]

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - {{native}}zeromq 4.2.*     # [not win]
    - {{native}}zeromq 4.1.*     # [win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rzmq')"           # [not win]
    - "\"%R%\" -e \"library('rzmq')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://github.com/ropensci/rzmq#readme (devel) http://www.zeromq.org (upstream)
  license: GPL-3
  summary: Interface to the 'ZeroMQ' lightweight messaging kernel (see <http://www.zeromq.org/>
    for more information).
  license_family: GPL3

extra:
  recipe-maintainers:
    - croth1
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: rzmq
# Title: R Bindings for 'ZeroMQ'
# Version: 0.9.3
# Authors@R: c( person("Whit", "Armstrong", , "armstrong.whit@gmail.com", role = "aut"), person("Jeroen", "Ooms", , "jeroen@berkeley.edu", role = c("aut", "cre")))
# Description: Interface to the 'ZeroMQ' lightweight messaging kernel (see <http://www.zeromq.org/> for more information).
# License: GPL-3
# Depends: R (>= 3.1.0)
# SystemRequirements: ZeroMQ >= 3.0.0: libzmq3-dev (deb) or zeromq3-devel (rpm)
# URL: http://github.com/ropensci/rzmq#readme (devel) http://www.zeromq.org (upstream)
# BugReports: http://github.com/ropensci/rzmq/issues
# NeedsCompilation: yes
# Packaged: 2017-10-01 20:43:27 UTC; jeroen
# Author: Whit Armstrong [aut], Jeroen Ooms [aut, cre]
# Maintainer: Jeroen Ooms <jeroen@berkeley.edu>
# Repository: CRAN
# Date/Publication: 2017-10-02 07:29:15 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
