travis:
  secure:
    BINSTAR_TOKEN: SORJKlWjPFpf+8T6yPXJ3GE+qVlSjV5S+wmar7TNm4xiGgxEoK5+xJJlTxkhjUbAF8IbxU2OAwuFcB1QNq+xPJLyyNWTyDH0//em8givW+2S18zlQC4X9hfms0lCpOHLwfJ3qnN8GfMXTXNoWzJCcHOwFR1Ou/etuqaD0nElpn+CoF6QrWXLvEGQfV1T4L0LMdB/Ah6psR0bv+kBX0E7jdu899kJpN6R4XtyqmiY/bMsIHtJhB3KovxeQsgVwIS9nFKg3pX+vZ1J78Fjvgi9Vn2d7nieeTVGe6JO525tD5oitcQtlTvGTFxAWDRnSojsN0CiCHUdP7MSqUnfz8H6IQyOcmyPtjDnYOBis3u7Hp4RI64ogenxIi9CKrlPEoPnl5dQ+JhWQaC0dDb7nEEUB73oeVxKUNP5w7H15ldIow5GyWdpe3PuMMONGSKHJHrv2K4PXU1rfCx74/SFL8AhAXpVtxgzmoGegOuZQcB1OckjHq9eMWgr997mVjp8oxC487V0BqESCKiTAXHeRw1gKUjM8XNxO2UEcWYa5oRRZs+fFortP6dPAtAreNfKCqmv7Rcvg6m3/VSj1313LVdlsHp0DWYbY2i6mVJQisVueDjMYXQgOpe27TgfaO6Kvta2brX/ffr2G0J/xJj6D13BZL0Mds0lN6+1CrQezBH53aU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
