travis:
  secure:
    BINSTAR_TOKEN: UG+Bei21xWCpGDPdSayLJ0GXJi6pJfVP5HlgOryJRzmpXZTC8wPi0mlOAwqE7Ev8A80nc+LqZWSDvN+ZKDOPVJdzTi1sW6I1KCjLA++R4Q3hcGUFxQOiJA4tPRHnWWyzQduOA3kZB3VELrCzQtQr7jlZVOHDYMFjpCY2I7xU0Kkx783n5EY0vNOvgM6lhIaLv0D/RDvqopCPojeahY+X1BwpHmTwcb9e3RBUtIoPbAt78AuSz1jl/fxTQdK/q7vPeifXxAq+Ey0IJZS5DzHe5dsF9XBut+JG0HB4x2O0m+vRJBK7hPt/8Ih/YDBEvDWLNRpd2RqYqXET3kWZ0zU3Wlfmebki0DvtcwW+PRApsc0Ebg24KENdFW2GyQhq4kXSoxN6ewyjwYyH1Mway9CjcslTdV9+zpsxt5aUG/LZm67UyTE0HPg2aJM4kBg6/gfX8kCUBpVLvAA3eM8olzwS9jhmNLIamPKfIk72ZAu+P8hB4JkhmeHHiGgzi7ozwC6VmCzuyZa/pj6RqwMNREHgm0GbjcsXcD7FDVtlKkX5N0L/yRPkgOD/dyNAoDY9340AKnhGQVHe+QXsR4zjwCbUWGkUkvocan+jgT+mw6azZDXbBMMmLo87ilqy1B4V4u545/a58zVcyOD2/MSQPEXhspmaIDBFoo5faIU368XOPlk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
